### ISSUE TITLE
Use "client_confguration" in nxt admin to get the app easily configurable

### ISSUE THREAD

**Issue by d-weeteling** [nens/crop-growth-app#11]
Currently, we can configure the app for each customer (i.e (as of (+/-) 03-2018): Bangladesh, Vietnam, Cambodia, Indonesia) by editing the constants.js file for each customer. This is somehwat hacky, which is due to the fact the customer base has grown organically; when starting the app it was meant solely for Vietnam, and the concept of variable config has evolved since then.

**Comment by Derryrover** [comment]
archive this repo
