### ISSUE TITLE
mapbox new token

### ISSUE THREAD

**Issue by Derryrover** [nens/crop-growth-app#20]
https://github.com/nens/crop-growth-app/search?q=eyJ1IjoibmVsZW5zY2h1dXJtYW5zIiwiYSI6ImhkXzhTdXcifQ.3k2-KAxQdyl5bILh_FioCw&unscoped_q=eyJ1IjoibmVsZW5zY2h1dXJtYW5zIiwiYSI6ImhkXzhTdXcifQ.3k2-KAxQdyl5bILh_FioCw

We need to change the the mapbox acces token for the background layers.

See below pr as example how the token needs to be changed:
https://github.com/nens/lizard-management-client/pull/458/files

This ticket is part of a bgger ticket to change all mapbox tokens for all our apps:
nens/threedi-live-site#476

**Comment by Derryrover** [comment]
For hints on how to make a build and a github release, have a look at the package.json.
Deploying works the same as for the other lizard clients.

**Comment by Derryrover** [comment]
@lexvand 
@hoanphungt 

Hi Hoan,
This crop growth app needs to have the mapbox acces token changed.
I can not add it to the current sprint, because the repo is not connected to our board.
kr Tom

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex,

I deployed the crop growth app to staging at here: https://nxt3.staging.lizard.net/clients/cropgrowth/#/. However, I couldn't see any tiles (chart or map) after selecting a region. It already happened like this to me before the release (both on staging and production). 

Could you please have a look when you have time?

**Comment by lexvand** [comment]
@hoanphungt Works on my computer.

**Comment by hoanphungt** [comment]
@lexvand 
Ah ok, I will deploy it to production then 👍

**Comment by hoanphungt** [comment]
@lexvand 
I just deployed it to production. Could you please check if it is still working correctly on production? here is the link: https://demo.lizard.net/clients/cropgrowth/#/ (version 0.0.14).

I checked and it loaded but no tile appeared just like on staging.

**Comment by lexvand** [comment]
Looking good:
![image](https://user-images.githubusercontent.com/5370809/94533705-cf5b6280-023f-11eb-818e-823a0e72258d.png)
